[zookeeper]
servers=[ "zookeeper:2181" ]
timeout=6
root-path="/burrow"

[client-profile.msk]
kafka-version="2.3.0"

[cluster.local]
client-profile="msk"
class-name="kafka"
servers=[ "kafka:9092" ]
topic-refresh=60
offset-refresh=30

[consumer.local]
class-name="kafka"
cluster="local"
servers=[ "kafka:9092" ]
group-blacklist="^(console-consumer-|python-kafka-consumer-).*$"
group-whitelist=""
client-profile="msk"
start-latest=true

[httpserver.default]
address=":8000"
